### ISSUE TITLE
is there a way to get the gate labels from the API ?

### ISSUE THREAD

**Issue by LucindaLanoy** [Cytobuoy/CyzFile-API#6]
After manual gating in CytoClus, it is possible to export the cyz files with the particles for each of the gates. Are the gate labels in the file and available via the CyzFile-API or must I get them from the filename please ?

**Comment by LievaartR** [comment]
CytoClus 4 and 5 have a slightly different approach to exporting information then CytoClus 3.  In CytoClus 3 you could indeed get
one file with for each particle to which gated set it belonged, CytoClus 4 on the other had generates a separate file for each gated set.  So instead of reading one file, you will have to load multiple files.  The exported filenames are create using:
```
<datafilename>_<gated set name>_<process>.csv
```
So e.g.
```
nano_cend16_20 2020-10-06 05u00_YellowBeads_Listmode.csv
```
Where the datafile name is ```nano_cend16_20 2020-10-06 05u00.cyz``` and the set is named ```YellowBeads```.

So if you run a batch export you will end up with a folder that contains a lot of files that you will have to open
to get the information for all the particles form all the files.
